title: "Portfolio - Ndeye Arame NIANG"
description: "Data Scientist | NLP Enthusiast | DevOps Learner"
#baseurl: "" # Important : le chemin relatif du projet
url: "https://Arame22.github.io"
theme: jekyll-theme-cayman
author: 
  name: "Ndeye Arame NIANG"
  email: "ng.niang1@outlook.fr"
  linkedin: "https://www.linkedin.com/in/ndeye-arame-niang"
  github: "https://github.com/Arame22/porfolio"
