title: "Portfolio - Ndeye Arame NIANG"
description: "Data Scientist | NLP Enthusiast | DevOps Learner"
baseurl: "" # Laissez vide pour GitHub Pages
url: "https://ndeye-arame-niang.github.io"
theme: jekyll-theme-cayman
author: 
  name: "Ndeye Arame NIANG"
  email: "ng.niang1@outlook.fr"
  linkedin: "https://www.linkedin.com/in/ndeye-arame-niang"
  github: "https://github.com/Arame22"
